[package]
name = "ApolloClient"
version = "0.3.12"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
    "!testUtils/",
    "!**/testing/**",
]
publish = true
[dependencies.GraphQL]
target = "https://github.com/roblox/graphql-lua"
version = "^15.6.0"

[dependencies.GraphQLTag]
target = "https://github.com/roblox/graphql-tag-lua"
package = "GraphqlTag"
version = "^2.12.6"

[dependencies.LuauPolyfill]
target = "https://github.com/roblox/luau-polyfill"
version = "^1"

[dependencies.LuauRegExp]
target = "https://github.com/roblox/luau-regexp"
package = "RegExp"
version = "^0.2.0"

[dependencies.Promise]
target = "https://github.com/roblox/roblox-lua-promise"
version = "^3.3.0"

[dependencies.React]
target = "https://github.com/roblox/roact-alignment"
version = "^17.0.1-rc.16"

[dependencies.RobloxRequests]
target = "https://github.com/roblox/roblox-requests"
version = "^0.1.0"

[dependencies.ZenObservable]
target = "https://github.com/roblox/zen-observable-lua"
version = "^0.8.16-roblox.2"
[dev_dependencies.Jest]
git = "https://github.com/roblox/jest-roblox"
package = "Jest"
rev = "v3.2.2"

[dev_dependencies.JestGlobals]
git = "https://github.com/roblox/jest-roblox"
package = "JestGlobals"
rev = "v3.2.2"

[dev_dependencies.ReactTestingLibrary]
git = "https://github.com/roblox/react-testing-library-lua"
rev = "main"
