[package]
name = "SignalsExperimental"
version = "0.6.0"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!jest.config.lua",
    "!**/__tests__/**",
]
publish = true
authors = ["Jonathan Kelaty <jkelaty@roblox.com>"]
[dependencies.Signals]
package = "Signals"
version = "^0.6.0"

[dependencies.SignalsScheduler]
package = "SignalsScheduler"
version = "^0.6.0"
[dev_dependencies.Jest]
version = "^3.12.0"

[dev_dependencies.JestGlobals]
version = "^3.12.0"
