[package]
name = "ReactOtter"
version = "1.3.7"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!*.spec.lua",
    "!**/__tests__/**",
]
publish = true
authors = ["Roblox"]
license = "MIT"
[dependencies.Otter]
package = "Otter"
version = "^1.3.7"

[dependencies.React]
target = "https://github.com/roblox/roact-alignment"
version = "^17.0.1-rc.19"
[dev_dependencies.Jest]
target = "https://github.com/roblox/jest-roblox"
version = "^3.2.5"

[dev_dependencies.JestGlobals]
target = "https://github.com/roblox/jest-roblox"
version = "^3.2.5"

[dev_dependencies.ReactTestingLibrary]
target = "https://github.com/roblox/react-testing-library-lua"
version = "^12.2.3"

[dev_dependencies.RoactCompat]
target = "https://github.com/roblox/roact-alignment"
version = "^17.0.1-rc.19"
