[package]
name = "FocusNavigation"
version = "2.0.0"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!**/__tests__",
]
publish = true
authors = ["Roblox"]
[dependencies.EventPropagation]
package = "EventPropagation"
version = "^2.0.0"

[dependencies.FocusNavigationUtils]
package = "FocusNavigationUtils"
version = "^2.0.0"

[dependencies.InputHandlers]
package = "InputHandlers"
version = "^2.0.0"
[dev_dependencies.Collections]
target = "https://github.com/roblox/luau-polyfill"
version = "^1.2"

[dev_dependencies.Jest]
target = "https://github.com/roblox/jest-roblox"
version = "^3.2.2"

[dev_dependencies.JestGlobals]
target = "https://github.com/roblox/jest-roblox"
version = "^3.3.0"
