[package]
name = "ZenObservable"
version = "0.8.16-roblox.2"
readme = "README.md"
content_root = "src"
files = ["*"]
publish = true
authors = [
    "Chris Trze≈õniewski <k.trzesniewski@gmail.com>",
    "Ignacio Falk <flakolefluk@gmail.com>",
    "Matt Hargett <plaztiksyke@gmail.com>",
    "Olivier Trepanier <otrepanier@roblox.com>",
    "Paul Doyle <pdoyle@roblox.com>",
    "Oluwole Adebiyi",
]
[dependencies.LuauPolyfill]
target = "https://github.com/roblox/luau-polyfill"
version = "^1.0.0"

[dependencies.Promise]
target = "https://github.com/roblox/roblox-lua-promise"
version = "^3.1.0"
[dev_dependencies.JestGlobals]
target = "https://github.com/roblox/jest-roblox"
version = "^2.4.1"
